version: "3"
services:
  api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: gradle.dockerfile
    ports:
      - "8080:8080"
    volumes: 
      - "./Backend:/srv"
    command: gradle bootRun 
  postgres:
    image: postgres:11-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    # restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped